<?php
require_once("config.php");
require_once("database.php");
require_once("db_object.php");
require_once("session.php");
require_once("adminuser.php");
require_once("staffuser.php");
require_once("employeeuser.php");
?>